language: node_js
node_js:
  - "node"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
os:
  - linux
  - osx
script: npm run test
cache:
  directories:
    - node_modules # NPM packages
matrix:
  fast_finish: true
